export const SET_LOADING = 'SET_LOADING';
export const UPDATE_CORONAVIRUS_DATA = 'UPDATE_CORONAVIRUS_DATA';
export const UPDATE_CORONAVIRUS_SETTING = 'UPDATE_CORONAVIRUS_SETTING';
export const UPDATE_SPLASH_LOGO = 'UPDATE_SPLASH_LOGO';
export const UPDATE_STATE = 'UPDATE_STATE';
export const UPDATE_LOCAL_STORAGE = 'UPDATE_LOCAL_STORAGE';
